### PR TITLE
Add feature to support tonic middleware

### PR DESCRIPTION
**Pull request by Guara92**
Hi!

I'm evaluating propelauth, but we use gRPC-web with `tonic`, so I added a convenient middleware to use your library with tonic.

bonus:
- Fixed clippy warnings
- Added link to the source code in the manifest
- runned `cargo fmt`

Please feel free to modify my proposal

### CODE REVIEW

**Comment by Emulator000** [comment]
any update regarding this?

**Review by Emulator000 — APPROVED** [review]

**Comment by Guara92** [comment]
@andrew-propelauth @itailevi98 are PR well-liked? Is there anything you don't like? Any feedback would be much appreciated

**Comment by Emulator000** [comment]
@andrew-propelauth @itailevi98 any update regarding this?

**Comment by andrew-propelauth** [comment]
Hey! Really sorry for the long delay here. We talked about it a bit internally and any frameworks that we add to our official library, we need to provide official support for (meaning docs, answering questions, keeping up to date with new versions, etc). 
At this time, we haven't gotten enough interest in Tonic to officially support it - but we are definitely going to maintain the base Rust crate to enable use cases like supporting frameworks like Tonic.

There are a few other changes in the PR that we are happy to merge (e.g. exposing metadata), but we can't take on official Tonic support at this time. Feel free to ping us at support@propelauth.com - happy to discuss further.

**Pull request closed without merging**
